//! Structured command metadata generated once from the reviewed Go v1.0.33 surface.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Arity {
    Any,
    Exact(usize),
    Maximum(usize),
}

#[derive(Clone, Copy, Debug)]
pub struct FlagSpec {
    pub long: &'static str,
    pub short: Option<char>,
    pub takes_value: bool,
    pub multiple: bool,
}

#[derive(Debug)]
pub struct CommandSpec {
    pub id: &'static str,
    pub path: &'static [&'static str],
    pub flags: &'static [FlagSpec],
    pub arity: Arity,
}

pub static COMMANDS: &[CommandSpec] = &[
    CommandSpec {
        id: "attachments",
        path: &["attachments"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "attachments-download",
        path: &["attachments", "download"],
        flags: &[],
        arity: Arity::Exact(1),
    },
    CommandSpec {
        id: "attachments-list",
        path: &["attachments", "list"],
        flags: &[
            FlagSpec {
                long: "format",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "import-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "json",
                short: None,
                takes_value: false,
                multiple: false,
            },
            FlagSpec {
                long: "project-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "recording-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "session-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "session-key",
                short: None,
                takes_value: true,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "auth",
        path: &["auth"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "auth-configure-api-key",
        path: &["auth", "configure-api-key"],
        flags: &[
            FlagSpec {
                long: "api-key",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "base-url",
                short: None,
                takes_value: true,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "auth-info",
        path: &["auth", "info"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "auth-login",
        path: &["auth", "login"],
        flags: &[FlagSpec {
            long: "base-url",
            short: None,
            takes_value: true,
            multiple: false,
        }],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "completion",
        path: &["completion"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "completion-bash",
        path: &["completion", "bash"],
        flags: &[FlagSpec {
            long: "no-descriptions",
            short: None,
            takes_value: false,
            multiple: false,
        }],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "completion-fish",
        path: &["completion", "fish"],
        flags: &[FlagSpec {
            long: "no-descriptions",
            short: None,
            takes_value: false,
            multiple: false,
        }],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "completion-powershell",
        path: &["completion", "powershell"],
        flags: &[FlagSpec {
            long: "no-descriptions",
            short: None,
            takes_value: false,
            multiple: false,
        }],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "completion-zsh",
        path: &["completion", "zsh"],
        flags: &[FlagSpec {
            long: "no-descriptions",
            short: None,
            takes_value: false,
            multiple: false,
        }],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "config",
        path: &["config"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "config-get",
        path: &["config", "get"],
        flags: &[],
        arity: Arity::Maximum(1),
    },
    CommandSpec {
        id: "config-set",
        path: &["config", "set"],
        flags: &[],
        arity: Arity::Maximum(2),
    },
    CommandSpec {
        id: "config-unset",
        path: &["config", "unset"],
        flags: &[],
        arity: Arity::Maximum(1),
    },
    CommandSpec {
        id: "data",
        path: &["data"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "data-coverage",
        path: &["data", "coverage"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "data-coverage-list",
        path: &["data", "coverage", "list"],
        flags: &[
            FlagSpec {
                long: "device-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "device-name",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "end",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "format",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "include-edge-recordings",
                short: None,
                takes_value: false,
                multiple: false,
            },
            FlagSpec {
                long: "json",
                short: None,
                takes_value: false,
                multiple: false,
            },
            FlagSpec {
                long: "project-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "recording-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "session-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "session-key",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "start",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "tolerance",
                short: None,
                takes_value: true,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "data-export",
        path: &["data", "export"],
        flags: &[
            FlagSpec {
                long: "compression",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "device-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "device-name",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "end",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "import-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "include-attachments",
                short: None,
                takes_value: false,
                multiple: false,
            },
            FlagSpec {
                long: "json",
                short: None,
                takes_value: false,
                multiple: false,
            },
            FlagSpec {
                long: "key",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "output-file",
                short: Some('o'),
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "output-format",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "project-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "recording-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "replay-lookback-seconds",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "replay-policy",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "session-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "session-key",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "start",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "topics",
                short: None,
                takes_value: true,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "data-import",
        path: &["data", "import"],
        flags: &[
            FlagSpec {
                long: "device-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "device-name",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "edge-recording-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "key",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "project-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "session-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "session-key",
                short: None,
                takes_value: true,
                multiple: false,
            },
        ],
        arity: Arity::Exact(1),
    },
    CommandSpec {
        id: "data-imports",
        path: &["data", "imports"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "data-imports-add",
        path: &["data", "imports", "add"],
        flags: &[
            FlagSpec {
                long: "device-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "device-name",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "edge-recording-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "key",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "project-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "session-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "session-key",
                short: None,
                takes_value: true,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "data-imports-list",
        path: &["data", "imports", "list"],
        flags: &[
            FlagSpec {
                long: "data-end",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "data-start",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "device-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "end",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "format",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "include-deleted",
                short: None,
                takes_value: false,
                multiple: false,
            },
            FlagSpec {
                long: "json",
                short: None,
                takes_value: false,
                multiple: false,
            },
            FlagSpec {
                long: "start",
                short: None,
                takes_value: true,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "devices",
        path: &["devices"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "devices-add",
        path: &["devices", "add"],
        flags: &[
            FlagSpec {
                long: "name",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "project-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "property",
                short: Some('p'),
                takes_value: true,
                multiple: true,
            },
            FlagSpec {
                long: "serial-number",
                short: None,
                takes_value: true,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "devices-edit",
        path: &["devices", "edit"],
        flags: &[
            FlagSpec {
                long: "name",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "project-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "property",
                short: Some('p'),
                takes_value: true,
                multiple: true,
            },
        ],
        arity: Arity::Exact(1),
    },
    CommandSpec {
        id: "devices-list",
        path: &["devices", "list"],
        flags: &[
            FlagSpec {
                long: "format",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "json",
                short: None,
                takes_value: false,
                multiple: false,
            },
            FlagSpec {
                long: "project-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "event-types",
        path: &["event-types"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "event-types-list",
        path: &["event-types", "list"],
        flags: &[
            FlagSpec {
                long: "format",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "json",
                short: None,
                takes_value: false,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "events",
        path: &["events"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "events-add",
        path: &["events", "add"],
        flags: &[
            FlagSpec {
                long: "device-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "end",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "event-type-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "metadata",
                short: Some('m'),
                takes_value: true,
                multiple: true,
            },
            FlagSpec {
                long: "start",
                short: None,
                takes_value: true,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "events-list",
        path: &["events", "list"],
        flags: &[
            FlagSpec {
                long: "device-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "device-name",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "end",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "event-type-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "format",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "json",
                short: None,
                takes_value: false,
                multiple: false,
            },
            FlagSpec {
                long: "limit",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "offset",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "query",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "query-field",
                short: None,
                takes_value: true,
                multiple: true,
            },
            FlagSpec {
                long: "sort-by",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "sort-order",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "start",
                short: None,
                takes_value: true,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "extensions",
        path: &["extensions"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "extensions-list",
        path: &["extensions", "list"],
        flags: &[
            FlagSpec {
                long: "format",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "json",
                short: None,
                takes_value: false,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "extensions-publish",
        path: &["extensions", "publish"],
        flags: &[],
        arity: Arity::Exact(1),
    },
    CommandSpec {
        id: "extensions-unpublish",
        path: &["extensions", "unpublish"],
        flags: &[],
        arity: Arity::Exact(1),
    },
    CommandSpec {
        id: "help",
        path: &["help"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "pending-imports",
        path: &["pending-imports"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "pending-imports-list",
        path: &["pending-imports", "list"],
        flags: &[
            FlagSpec {
                long: "device-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "device-name",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "error",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "filename",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "format",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "json",
                short: None,
                takes_value: false,
                multiple: false,
            },
            FlagSpec {
                long: "key",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "project-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "request-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "session-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "session-key",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "show-completed",
                short: None,
                takes_value: false,
                multiple: false,
            },
            FlagSpec {
                long: "show-quarantined",
                short: None,
                takes_value: false,
                multiple: false,
            },
            FlagSpec {
                long: "site-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "updated-since",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "without-project",
                short: None,
                takes_value: false,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "projects",
        path: &["projects"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "projects-list",
        path: &["projects", "list"],
        flags: &[
            FlagSpec {
                long: "format",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "json",
                short: None,
                takes_value: false,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "recordings",
        path: &["recordings"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "recordings-delete",
        path: &["recordings", "delete"],
        flags: &[],
        arity: Arity::Exact(1),
    },
    CommandSpec {
        id: "recordings-list",
        path: &["recordings", "list"],
        flags: &[
            FlagSpec {
                long: "device-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "device-name",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "edge-site-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "end",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "format",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "import-status",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "json",
                short: None,
                takes_value: false,
                multiple: false,
            },
            FlagSpec {
                long: "limit",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "offset",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "path",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "project-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "session-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "session-key",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "site-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "sort-by",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "sort-order",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "start",
                short: None,
                takes_value: true,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "root",
        path: &[],
        flags: &[
            FlagSpec {
                long: "client-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "config",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "debug",
                short: None,
                takes_value: false,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "sessions",
        path: &["sessions"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "sessions-add",
        path: &["sessions", "add"],
        flags: &[
            FlagSpec {
                long: "device-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "name",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "project-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "sessions-delete",
        path: &["sessions", "delete"],
        flags: &[FlagSpec {
            long: "project-id",
            short: None,
            takes_value: true,
            multiple: false,
        }],
        arity: Arity::Exact(1),
    },
    CommandSpec {
        id: "sessions-get",
        path: &["sessions", "get"],
        flags: &[FlagSpec {
            long: "project-id",
            short: None,
            takes_value: true,
            multiple: false,
        }],
        arity: Arity::Exact(1),
    },
    CommandSpec {
        id: "sessions-list",
        path: &["sessions", "list"],
        flags: &[
            FlagSpec {
                long: "device-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "device-name",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "format",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "json",
                short: None,
                takes_value: false,
                multiple: false,
            },
            FlagSpec {
                long: "project-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "sessions-recordings",
        path: &["sessions", "recordings"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "sessions-recordings-add",
        path: &["sessions", "recordings", "add"],
        flags: &[FlagSpec {
            long: "project-id",
            short: None,
            takes_value: true,
            multiple: false,
        }],
        arity: Arity::Exact(2),
    },
    CommandSpec {
        id: "sessions-recordings-list",
        path: &["sessions", "recordings", "list"],
        flags: &[FlagSpec {
            long: "project-id",
            short: None,
            takes_value: true,
            multiple: false,
        }],
        arity: Arity::Exact(1),
    },
    CommandSpec {
        id: "sessions-recordings-remove",
        path: &["sessions", "recordings", "remove"],
        flags: &[FlagSpec {
            long: "project-id",
            short: None,
            takes_value: true,
            multiple: false,
        }],
        arity: Arity::Exact(2),
    },
    CommandSpec {
        id: "topics",
        path: &["topics"],
        flags: &[],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "topics-list",
        path: &["topics", "list"],
        flags: &[
            FlagSpec {
                long: "device-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "device-name",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "end",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "format",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "include-schemas",
                short: None,
                takes_value: false,
                multiple: false,
            },
            FlagSpec {
                long: "json",
                short: None,
                takes_value: false,
                multiple: false,
            },
            FlagSpec {
                long: "limit",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "offset",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "project-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "recording-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "recording-key",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "session-id",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "session-key",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "sort-by",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "sort-order",
                short: None,
                takes_value: true,
                multiple: false,
            },
            FlagSpec {
                long: "start",
                short: None,
                takes_value: true,
                multiple: false,
            },
        ],
        arity: Arity::Any,
    },
    CommandSpec {
        id: "version",
        path: &["version"],
        flags: &[],
        arity: Arity::Any,
    },
];

pub fn by_id(id: &str) -> Option<&'static CommandSpec> {
    COMMANDS.iter().find(|spec| spec.id == id)
}
pub fn by_path(path: &[String]) -> Option<&'static CommandSpec> {
    COMMANDS.iter().find(|spec| spec.path == path)
}
